package com.booking.entities.model.hotels

data class Details(
    val address: Address,
    val checkInTime: String,
    val checkOutTime: String,
    val cityCenterPointDistance: Double,
    val cityCenterPointDistanceName: String,
    val coordinate: Coordinate,
    val covidInfo: Any,
    val description: String,
    val domestic: Boolean,
    val extra: Extra,
    val facilitiesGroup: List<Any>,
    val generalReviewScoreNote: String,
    val hotelAutocompleteIcon: String,
    val hotelConcept: List<Any>,
    val hotelDescriptions: List<Any>,
    val hotelInfoDescription: Any,
    val id: Any,
    val imageTypes: List<Any>,
    val images: List<Any>,
    val locationDistance: Any,
    val name: String,
    val nearByHotels: Any,
    val policies: Policies,
    val reviewInfo: Any,
    val reviewScore: Int,
    val reviewScoreLocalized: String,
    val reviews: Any,
    val reviewsTotalCount: Any,
    val slug: String,
    val starRating: Int,
    val suitabilities: List<Any>
)