package com.booking.entities.model.hotels

data class Offer(
    val alerts: List<Any>,
    val allotment: Int,
    val buttonMessages: List<Any>,
    val cancellationRules: List<Any>,
    val comment: Any,
    val concept: Concept,
    val discountFrom: Int,
    val discountTags: Any,
    val displayedCurrency: String,
    val freeChildAgeHotelDetail: List<Any>,
    val freeChildAgeRange: Any,
    val guest: Guest,
    val hasCancellationRule: Boolean,
    val hash: String,
    val hotelOfferBonusScRate: HotelOfferBonusScRate,
    val information: List<Any>,
    val isCheapestOffer: Boolean,
    val isMemberOnlyDeal: Boolean,
    val isPossibleChange: Boolean,
    val isRefundable: Boolean,
    val isSaleable: Boolean,
    val needsCheck: Boolean,
    val needsCheckBeforeBooking: Boolean,
    val offerType: String,
    val payAtHotel: Boolean,
    val price: Int,
    val priceBreakDowns: List<Any>,
    val provider: Int,
    val refundableExpireDate: RefundableExpireDate,
    val roomClass: RoomClass,
    val sourceOfferType: String
)